"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['taskbridge/gui/app.py']
DATA_FILES = [
    ('taskbridge/gui/assets', [
        'taskbridge/gui/assets/bridge_animated_black.gif',
        'taskbridge/gui/assets/bridge_animated_white.gif',
        'taskbridge/gui/assets/bridge_black.png',
        'taskbridge/gui/assets/bridge_white.png',
        'taskbridge/gui/assets/refresh.png',
        'taskbridge/gui/assets/TaskBridge.png',
        'taskbridge/gui/assets/trash.png'
        ]
     )
]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
