# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(310, 164)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbl_taskbridge_logo = QtWidgets.QLabel(parent=Dialog)
        self.lbl_taskbridge_logo.setMinimumSize(QtCore.QSize(64, 64))
        self.lbl_taskbridge_logo.setMaximumSize(QtCore.QSize(64, 64))
        self.lbl_taskbridge_logo.setScaledContents(True)
        self.lbl_taskbridge_logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_taskbridge_logo.setObjectName("lbl_taskbridge_logo")
        self.horizontalLayout.addWidget(self.lbl_taskbridge_logo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lbl_version = QtWidgets.QLabel(parent=Dialog)
        self.lbl_version.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_version.setObjectName("lbl_version")
        self.verticalLayout.addWidget(self.lbl_version)
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_taskbridge_logo.setText(_translate("Dialog", "TaskBridge"))
        self.label_2.setText(_translate("Dialog", "TaskBridge"))
        self.lbl_version.setText(_translate("Dialog", "Version 0.1.0"))
        self.label_4.setText(_translate("Dialog", "Copyright © 2024 Keith Vassallo"))
